[package]
authors = [
  "Toshiaki Takada <toshi@reze.rs>",
  "Valentin Kivachuk Burda <foss@vk496.es>",
]
edition = "2021"
name = "utils"
version = "0.3.0"

[dependencies]
nix = "0.17.0"
sysrepo = {path = "../.."}
