[package]
authors = [
  "Toshiaki Takada <toshi@reze.rs>",
  "Valentin Kivachuk Burda <foss@vk496.es>",
]
edition = "2021"
name = "rpc_subscribe"
version = "0.3.0"

[dependencies]
libc = "0.2.70"
sysrepo = {path = "../.."}
utils = {path = "../utils"}
