[package]
authors = ["Toshiaki Takada <toshi@reze.rs>", "Florian Kauer <florian.kauer@linutronix.de>"]
edition = "2021"
name = "sr_get_data"
version = "0.3.0"

[dependencies]
sysrepo = {path = "../.."}
yang3 = { version = "0.16.0" }
